<#1>
<?php
\srag\Plugins\ChangeLog\LogEntry\Deletion\ChangeLogDeletionEntry::updateDB();
?>
<#2>
<?php
\srag\Plugins\ChangeLog\LogEntry\Modification\ChangeLogModification::updateDB();
\srag\Plugins\ChangeLog\LogEntry\Modification\ChangeLogModificationEntry::updateDB();
?>
<#3>
<?php
\srag\Plugins\ChangeLog\LogEntry\Modification\ChangeLogModification::updateDB();
?>
<#4>
<?php
\srag\Plugins\ChangeLog\Config\ChangeLogConfig::updateDB();
?>
<#5>
<?php
\srag\Plugins\ChangeLog\LogEntry\Modification\ChangeLogModificationEntry::updateDB();
?>
